pylint suggestions and refactor
splunk/splunk-connect-for-snmp-poller pull request #117
Opened 2021-09-09 08:53 UTC by okuzhel-splunk

*pylint suggestions
*refactor and simplification

2021-09-09 09:04 UTC, weliasz commented on BUILD_STEPS.md
> +> This file is being used as a reference steps while working on development aspects of SNMP Poller component of Splunk Connect for SNMP!
https://ell.stackexchange.com/questions/23800/is-still-being-used-versus-is-still-used
"It is being used" means that someone is using it at the moment.
I don't see a need to change this.

2021-09-09 09:04 UTC, weliasz approved these changes

2021-09-13 08:01 UTC, omrozowicz-splunk requested changes
Can you install pre-commit locally:

2021-09-13 15:02 UTC, arys-splunk commented
> Please install pre-commit locally and run `pre-commit run --all-files` so it lints everything up to match requirements of our CI.

Additional comment here: let's add `pylint` in a `pre-commit` configuration instead of adding it as a dev dependency to the package itself.

2021-09-14 08:07 UTC, closed without merging