logger changes
splunk/splunk-connect-for-snmp-poller pull request #131
Opened 2021-09-29 14:12 UTC by okuzhel-splunk

* Reviewed logging and changed not needed info logs to debug or error
* Tested on HELM deployment that changes in config logging level is working

2021-09-29 14:17 UTC, weliasz requested changes
Looks great. I'd also change default="debug" to "info" in parse_command_line_arguments in utilities.py. I think this is overriden in kubernetes config but MIB and trap has the default set to info so I think we should change in poller too.

2021-09-29 14:22 UTC, okuzhel-splunk commented
> Looks great. I'd also change default="debug" to "info" in parse_command_line_arguments in utilities.py. I think this is overriden in kubernetes config but MIB and trap has the default set to info so I think we should change in poller too.

@weliasz good idea! changed

2021-09-29 14:25 UTC, weliasz approved these changes

2021-09-30 07:03 UTC, merged

2021-10-05 06:54 UTC, rfaircloth-splunk commented
:tada: This PR is included in version 1.5.0-develop.9 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-snmp-poller/releases/tag/v1.5.0-develop.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: