feat: extract enricher data from config
splunk/splunk-connect-for-snmp-poller pull request #97
Opened 2021-07-29 11:56 UTC by lstoppa

2021-07-29 11:56 UTC, lstoppa commented
I have read the Code of Conduct and I hereby accept the Terms

2021-07-29 12:10 UTC, lstoppa commented
I have read the Code of Conduct and I hereby accept the Terms

2021-07-29 12:10 UTC, lstoppa commented
I have read the Code of Conduct and I hereby accept the Terms

2021-07-29 12:17 UTC, lstoppa commented
I have read the Code of Conduct and I hereby accept the Terms

2021-07-29 12:33 UTC, lstoppa commented
I have read the Code of Conduct and I hereby accept the Terms

2021-08-10 09:23 UTC, omrozowicz-splunk requested changes

2021-08-10 09:23 UTC, omrozowicz-splunk commented on splunk_connect_for_snmp_poller/manager/static/mib_enricher.py
> +#
We have duplicated license here

2021-08-10 09:23 UTC, omrozowicz-splunk commented on splunk_connect_for_snmp_poller/manager/poller.py
> +    # snmp_polling(host, version, community, profile, server_config, splunk_indexes)
Let's delete this comment as we already have it

2021-08-10 09:23 UTC, omrozowicz-splunk commented on splunk_connect_for_snmp_poller/manager/static/mib_enricher.py
> +            if len(additional_if_mib_dimensions) > 0:
if additional_if_mib_dimensions is a list then:
```
if additional_if_mib_dimensions:
```
is enough

2021-08-19 07:42 UTC, weliasz requested changes
How about adding integration test that will show enriched data in Splunk?

2021-08-19 09:45 UTC, omrozowicz-splunk commented on splunk_connect_for_snmp_poller/manager/static/__init__.py
> +#
> Python tools out there such as mypy and pytest require empty __init__.py files to interpret the code structure accordingly.

2021-08-19 09:45 UTC, omrozowicz-splunk commented on splunk_connect_for_snmp_poller/manager/static/mib_enricher.py
> +        if metric_name and metric_name.startswith(InterfaceMib.IF_MIB_METRIC_SUFFIX):
Changed it

2021-08-19 09:48 UTC, weliasz approved these changes

2021-08-19 09:54 UTC, weliasz approved these changes

2021-08-19 10:00 UTC, omrozowicz-splunk approved these changes

2021-08-19 10:10 UTC, weliasz approved these changes

2021-08-19 10:10 UTC, merged

2021-08-24 10:12 UTC, rfaircloth-splunk commented
:tada: This PR is included in version 1.5.0-develop.3 :tada:

The release is available on [GitHub release](https://github.com/splunk/splunk-connect-for-snmp-poller/releases/tag/v1.5.0-develop.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: